import Foundation
import AppKit

/// Writes an executable `.command` file that starts `mlx_lm.server` with a
/// user-chosen model and opens it in Terminal. This is a deliberate
/// workaround for the macOS app sandbox: we never call `Process.run`
/// ourselves (which would require relaxing the sandbox); instead, we hand
/// a script to the OS via `NSWorkspace.open`, which routes it to Terminal
/// — an unsandboxed agent — and that's what executes the server.
///
/// Two modes:
/// - **foreground** — `exec`s the server in the Terminal window. Closing
///   that window kills the server. Simple and explicit.
/// - **background** — `nohup`s the server into a log file and records its
///   PID. The user can close Terminal immediately and the server keeps
///   running. Stopping requires the separate stop script below, which
///   reads the PID and sends SIGTERM.
enum ServerLauncher {

    struct Config: Equatable {
        /// Model identifier or on-disk path accepted by `mlx_lm.server --model`.
        var modelPath: String
        /// Optional Python virtualenv to `source` before running the server.
        /// Pass an empty string to skip and use whatever is on the user's PATH.
        var pythonVenvPath: String
        /// Port the server should listen on, derived from the configured
        /// base URL in `AppSettings`.
        var port: Int
        /// When `true`, the rendered script detaches the server and exits
        /// quickly so the Terminal window can close without killing it.
        var background: Bool = false
        /// Absolute path where the background-mode script should write its
        /// PID, and where the stop script should read it from. Ignored in
        /// foreground mode. Must be an absolute path from the un-sandboxed
        /// Terminal's perspective (use `URL.path`).
        var pidFilePath: String = ""
        /// Absolute path for the background-mode log file.
        var logFilePath: String = ""
    }

    // MARK: - Script rendering

    /// Render the shell script without performing any I/O. Split out of
    /// `write(_:to:)` so tests can assert content independently.
    static func renderScript(_ config: Config) -> String {
        let trimmedVenv = config.pythonVenvPath
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let model = shellEscape(config.modelPath)

        var lines: [String] = [
            "#!/bin/bash",
            "# Generated by LocalMLX — do not edit by hand.",
            "set -eu",
        ]

        if config.background {
            let pidFile = shellEscape(config.pidFilePath)
            let logFile = shellEscape(config.logFilePath)

            lines += [
                "# Background mode: the server is detached so closing",
                "# this Terminal window does NOT kill it.",
                "mkdir -p \"$(dirname \(logFile))\"",
                "mkdir -p \"$(dirname \(pidFile))\"",
                "echo 'LocalMLX → starting mlx_lm.server in background on port \(config.port)…'",
            ]
            if !trimmedVenv.isEmpty {
                let venv = shellEscape(trimmedVenv)
                lines.append("source \(venv)/bin/activate")
            }
            lines += [
                "nohup mlx_lm.server --model \(model) --port \(config.port) >> \(logFile) 2>&1 &",
                "SERVER_PID=$!",
                "echo \"$SERVER_PID\" > \(pidFile)",
                "echo",
                "echo \"Server PID: $SERVER_PID\"",
                "echo \"Log: $(eval echo \(logFile))\"",
                "echo",
                "echo 'You can close this Terminal window — the server will keep running.'",
                "echo 'Use the Stop Server button in LocalMLX Settings to stop it later.'",
                "sleep 2",
            ]
        } else {
            lines += [
                "# Foreground mode: closing this Terminal window stops the server.",
                "echo 'LocalMLX → starting mlx_lm.server on port \(config.port)…'",
            ]
            if !trimmedVenv.isEmpty {
                let venv = shellEscape(trimmedVenv)
                lines.append("source \(venv)/bin/activate")
            }
            lines.append("exec mlx_lm.server --model \(model) --port \(config.port)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Render a bootstrap script for users who don't yet have MLX
    /// installed. Creates a virtualenv (default: ~/mlx-env), installs
    /// `mlx-lm`, and prints final setup instructions pointing back at
    /// the LocalMLX Settings fields. This runs in the foreground because
    /// the user needs to see pip's output and any errors.
    static func renderInstallScript(venvPath: String = "$HOME/mlx-env") -> String {
        let venv = shellEscape(venvPath)
        return """
        #!/bin/bash
        # Generated by LocalMLX — installs mlx-lm into a fresh virtualenv.
        set -eu

        echo 'LocalMLX → setting up MLX…'
        echo

        # --- Python check ---
        if ! command -v python3 >/dev/null 2>&1; then
          echo 'Python 3 is required. The easiest way to get it on macOS:'
          echo '  brew install python@3.12'
          echo
          echo '…or grab the installer from https://www.python.org/downloads/'
          exit 1
        fi
        echo "Python: $(python3 --version)"

        VENV=\(venv)

        # --- Virtualenv ---
        if [ -d "$VENV" ]; then
          echo "Reusing existing virtualenv at $VENV"
        else
          echo "Creating virtualenv at $VENV"
          python3 -m venv "$VENV"
        fi

        # shellcheck disable=SC1091
        source "$VENV/bin/activate"
        python -m pip install --upgrade pip
        python -m pip install mlx-lm

        echo
        echo '=============================================='
        echo 'Done! mlx-lm is installed.'
        echo
        echo 'Now, in LocalMLX Settings → Server:'
        echo "  1. Set  Python venv  →  $VENV"
        echo '  2. Set  Model        →  mlx-community/Llama-3.2-3B-Instruct-4bit'
        echo '                           (or any other mlx-community model)'
        echo '  3. Click  Start Server'
        echo
        echo 'Press any key to close this window.'
        read -n 1 -s
        """ + "\n"
    }

    /// Render a small companion script that stops a previously-started
    /// background server by sending SIGTERM to the PID recorded in the
    /// PID file. Falls through quietly if no server is running.
    static func renderStopScript(pidFilePath: String) -> String {
        let pidFile = shellEscape(pidFilePath)
        let lines: [String] = [
            "#!/bin/bash",
            "# Generated by LocalMLX — stops a background mlx_lm.server.",
            "set -eu",
            "PIDFILE=\(pidFile)",
            "if [ ! -f \"$PIDFILE\" ]; then",
            "  echo 'No LocalMLX server PID file found — nothing to stop.'",
            "  sleep 2",
            "  exit 0",
            "fi",
            "PID=$(cat \"$PIDFILE\")",
            "if kill -0 \"$PID\" 2>/dev/null; then",
            "  kill \"$PID\"",
            "  echo \"Sent SIGTERM to mlx_lm.server (PID $PID).\"",
            "else",
            "  echo \"Recorded PID $PID is not running.\"",
            "fi",
            "rm -f \"$PIDFILE\"",
            "sleep 2",
        ]
        return lines.joined(separator: "\n") + "\n"
    }

    /// Single-quote escape a path/identifier for safe embedding in bash.
    /// Keeps the implementation defensive against model paths with spaces
    /// or special characters.
    static func shellEscape(_ string: String) -> String {
        "'" + string.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Paths

    /// Directory inside the app's Application Support container for all
    /// launcher artifacts (scripts, PID file). Created on access.
    static func supportDirectory() throws -> URL {
        let fm = FileManager.default
        let base = try fm.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true)
        let dir = base.appendingPathComponent("LocalMLX", isDirectory: true)
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    /// Default locations for the generated scripts + PID/log files. Log
    /// goes under `~/Library/Logs/LocalMLX/` by convention so it's easy
    /// to find outside the app's sandbox container.
    struct DefaultPaths {
        var startScript: URL
        var stopScript: URL
        var pidFile: URL
        var logFile: URL
    }

    static func defaultPaths() throws -> DefaultPaths {
        let support = try supportDirectory()
        let logsRoot = try FileManager.default.url(
            for: .libraryDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: false)
            .appendingPathComponent("Logs", isDirectory: true)
            .appendingPathComponent("LocalMLX", isDirectory: true)

        return DefaultPaths(
            startScript: support.appendingPathComponent("start-mlx-server.command"),
            stopScript: support.appendingPathComponent("stop-mlx-server.command"),
            pidFile: support.appendingPathComponent("server.pid"),
            logFile: logsRoot.appendingPathComponent("server.log")
        )
    }

    // MARK: - File I/O

    /// Write the rendered script to `url` and mark it executable.
    /// Returns the URL so the caller can chain to `launch(_:)`. Split
    /// from `launch` so unit tests can verify content + permissions
    /// without actually spawning Terminal.
    @discardableResult
    static func write(_ script: String, to url: URL) throws -> URL {
        try script.write(to: url, atomically: true, encoding: .utf8)
        var attrs = try FileManager.default.attributesOfItem(atPath: url.path)
        attrs[.posixPermissions] = NSNumber(value: 0o755)
        try FileManager.default.setAttributes(attrs, ofItemAtPath: url.path)
        return url
    }

    /// Hand the command file to Launch Services so Terminal runs it.
    /// `activates = false` asks Launch Services not to bring Terminal to
    /// the front, so LocalMLX keeps focus and Terminal opens behind it
    /// (or on another Space). Terminal still shows its window — the
    /// sandbox leaves us no way to avoid that entirely without shipping
    /// a dedicated helper binary.
    static func launch(_ url: URL) {
        let config = NSWorkspace.OpenConfiguration()
        config.activates = false
        NSWorkspace.shared.open(url, configuration: config, completionHandler: nil)
    }

    /// Convenience: write a start script for `config` to the default
    /// location and open it in Terminal. `config`'s `pidFilePath` and
    /// `logFilePath` are overwritten with the default paths. Returns the
    /// script URL for feedback.
    @discardableResult
    static func writeAndLaunch(_ config: Config) throws -> URL {
        let paths = try defaultPaths()
        var populated = config
        populated.pidFilePath = paths.pidFile.path
        populated.logFilePath = paths.logFile.path
        let script = renderScript(populated)
        _ = try write(script, to: paths.startScript)
        launch(paths.startScript)
        return paths.startScript
    }

    /// Convenience: write and open the stop script targeting the default
    /// PID file. Returns the stop-script URL.
    @discardableResult
    static func writeAndLaunchStop() throws -> URL {
        let paths = try defaultPaths()
        let script = renderStopScript(pidFilePath: paths.pidFile.path)
        _ = try write(script, to: paths.stopScript)
        launch(paths.stopScript)
        return paths.stopScript
    }

    /// Convenience: write and open the MLX install bootstrap script.
    /// Uses the default `~/mlx-env` virtualenv target. Returns the
    /// script URL so the UI can show "opened in Terminal" feedback.
    @discardableResult
    static func writeAndLaunchInstall() throws -> URL {
        let support = try supportDirectory()
        let url = support.appendingPathComponent("install-mlx.command")
        let script = renderInstallScript()
        _ = try write(script, to: url)
        launch(url)
        return url
    }
}
